### ISSUE TITLE
想找Demo的同学,可以在Fork里发现新大陆

### ISSUE THREAD

**Issue by xiky** [gsdios/GSD_ZHIFUBAO#7]

**Comment by CoderMikeHe** [comment]
怎么弄。能否给我个压缩包，491273090@qq.com，谢谢！仅限学习

**Comment by beforeold** [comment]
@CoderMikeHe 看看右上角Fork，点击数字，在删除以前有其他同学fork了，我已经找到了，不过我当然不会发给你发包了，谁好意思做伸手党呢。

**Comment by CoderMikeHe** [comment]
恩恩，多谢哈。

**Comment by zcb1603999** [comment]
删除只是一次提交，只要库还在，克隆下来git head移动到删除之前不就行了，这就是git的强大之处

**Comment by beforeold** [comment]
顶楼上 @zcb1603999，是时候安利一波 廖雪峰老师的 [Git教程了](https://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000)

**Comment by MQL9011** [comment]
想知道这个库是干嘛的

**Comment by huangbingke** [comment]
我想知道这个库是干嘛的
